### ISSUE TITLE
p-value accuracy in R script

### ISSUE THREAD

**Issue by nievergeltlab** [e-jorsboe/asaMap#2]
Hi,

The R script for getting p-values is 

return(1-pchisq(-2*(col1-col2),df=df))

however very significant p-values ( p < 2.2e-16) will be given value 0 instead of their true value.

to avoid this, I suggest just using pchisq function to get the upper tail of the distribution directly, i.e.

return(pchisq(-2*(col1-col2),df=df,lower.tail=F))

bw
adam

**Comment by e-jorsboe** [comment]
Hi Adam, 

Thank you for your suggestion! You are right this provides a better way of reporting the P-values. I have therefore incorporated your suggestion.

So thank you for the input!
